"""Add buried_date to Deceased

Revision ID: add_buried_date_20250115
Revises: relational_update_20250921
Create Date: 2025-01-15
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_buried_date_20250115'
down_revision = 'relational_update_20250921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deceased', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buried_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deceased', schema=None) as batch_op:
        batch_op.drop_column('buried_date')

    # ### end Alembic commands ###